### ISSUE TITLE
Unable to make full download after 4/18 update (Ver 1.0.91) in JP server

### ISSUE THREAD

**Issue by Hankerlx** [Sanfrag/Crave-Saga-Client#1]
Unable to make full download nor extract resource from client after update to Ver 1.0.91 on 4/18/2024. It seems that the client does not recognize the new version? Provider: FANZA GAMES
![image](https://github.com/Sanfrag/Crave-Saga-Client/assets/55601596/9f8f6164-fdb7-4d34-aba2-fdaba2b77742)

**Comment by Sanfrag** [comment]
Should be fixed. Check release.
