### ISSUE TITLE
Can not connect to the the EROLABS version

### ISSUE THREAD

**Issue by Blasetvrt** [Sanfrag/Crave-Saga-Client#2]
EROLABS version gives ERR_SSL_VERSION_OR_CIPHER_MISMATCH error in different devices since recently

![image](https://github.com/Sanfrag/Crave-Saga-Client/assets/39378481/5dbdb523-5d1c-4f41-83ea-83422ec738ab)

**Comment by Kumu221** [comment]
same

**Comment by Sanfrag** [comment]
I replied to some discord messages and totally forgot about here.

Anyway, if you right-click the erolabs icon in the provider selector, you can switch the provider URL to `www.ero-labs.com` or `www.ero-labs.website`. The default URL is having some weird configuration on their side so I don't know what is causing it to be honest.

**Comment by Sanfrag** [comment]
the default URL has been changed in 0.1.7
